### ISSUE TITLE
Add `@gql_str` macro

### ISSUE THREAD

**Issue by pfitzseb** [DeloitteDigitalAPAC/GraphQLClient.jl#6]
A `gql"query () ..."` macro would have a few advantages:
1. Don't need to escape `$`s
2. Can do some basic checks, e.g. throw an error when variables are not declared properly or the query is malformed
3. Makes syntax highlighting possible in editors/GH

**Comment by mmiller-max** [comment]
Great idea!

**Comment by mmiller-max** [comment]
What does the macro need to do to enable the syntax highlighting? Is there an example you can point me too?

**Comment by pfitzseb** [comment]
Nothing on your end, but I can add a rule to https://github.com/JuliaEditorSupport/atom-language-julia.

**Comment by mmiller-max** [comment]
> Nothing on your end, but I can add a rule to https://github.com/JuliaEditorSupport/atom-language-julia.

Sounds good.

Had a bit more of a think about this and the checking of string is actually difficult due to the variety available in the GraphQL schema.

So I reckon a good course of action is to get in a simple version of this that has minimal checking but at least lets it be used, and then can work on the checking separately/incrementally (effectively means writing a parser to do anything other than simple checks).

**Comment by mmiller-max** [comment]
@pfitzseb sorry for the delay in getting this in. I'm pretty much there with a [parser](https://github.com/mmiller-max/GraphQLParser.jl) that I think I can simplify and use to do some decent checking in the string macro. I'll add that to the PR and then go from there.

**Comment by mmiller-max** [comment]
@pfitzseb got this in now - let me know if I can help with the syntax highlighting at all
